---
# tasks file for /mnt/c/Users/shirl/Desktop/Cours/EPF/4A/DevOps/ansible/roles/app
- name: Pull the API Image
  docker_image:
    name: shirleybayle/tp-devops-simple-api
    tag: latest
    source: pull
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Run API Container
  docker_container:
    name: myStudentApi
    image: shirleybayle/tp-devops-simple-api:latest
    networks:
      - name: app-network
  vars:
    ansible_python_interpreter: /usr/bin/python3