name: CI Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI Test Backend"]
    types:
      - completed
      

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && success() # Only run on main and if test-backend is successful
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./Java/api/simple-api-student-main
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./Postgres
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./Java/server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true
